export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import "@styles/global.scss";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl" prefix="og: https://ogp.me/ns#">
      <body>{children}</body>
    </html>
  );
}
